name: Terraform

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    #environment: production

# Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
  
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v3
    
    - name: Display structure of downloaded files
      run: ls -R

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check
    
    - name: Terraform Plan
      run: terraform plan -input=false
    
    